export const foodData = [

    {
        id:1,
      image: '/jrice1.jpg',
      description: 'Smoky, spicy, and perfectly seasoned African perfection',
      price: '26.99',
      name: 'Jollof Rice',
      fullDescription: 'A vibrant, long-grain parboiled rice masterpiece, infused with a signature smokey aroma and seasonings , every forkful delivers a perfect balance of heat and savory soul',
      protein: true,
      category: 'rice'

    },
    {
        id:2,
      image: '/fried2.jpg',
      description: 'Savory golden grains stir-fried with crisp vegetables and aromatic spices.',
      price: '25.99',
      name: 'Fried Rice',
      fullDescription: 'Aromatic golden grains stir-fried with vibrant vegetables, seasoned liver, and exotic spices for a savory, colorful, and truly satisfying meal.',
      category: 'rice',
      protein: true
    },
    {
        id:3,
      image: '/coconut1.jpg',
      description: 'Fragrant rice simmered in rich coconut milk with succulent seafood.',
      price: '26.99',
      name: 'coconut rice',
      fullDescription: 'Fragrant rice infused with rich coconut milk, sautéed shrimp, and sweet peppers for a creamy, tropical, and deeply flavorful experience.',
      category: 'rice',
      protein: true
    },
    {
        id:4,
      image: '/ofada1.jpg',
      description: 'Spicy green pepper sauce with assorted meats served over fluffy rice',
      price: '25.00',
      name: 'Ayamase Sauce w/White Rice',
      fullDescription: 'Bold green chili sauce simmered with fermented locust beans and assorted meats, served alongside perfectly steamed, fluffy white rice.',
      category: 'rice',
      protein: false
    },
    {
        id:5,
      image: '/stew1.jpg',
      description: 'Fluffy white rice served with a rich, savory tomato-based stew.',
      price: '20.00',
      name: 'White Rice & Stew',
      fullDescription: 'Perfectly steamed fluffy white rice paired with a vibrant, slow-cooked tomato and pepper stew seasoned with traditional aromatic spices',
      category: 'rice',
      protein: false
    },
    {
        id:6,
      image: '/jtray1.jpg',
      description: 'Perfectly steamed fluffy white rice paired with a vibrant, slow-cooked tomato and pepper stew seasoned with traditional aromatic spices',
      price: '50.00',
      name: 'Jollof Rice Tray',
      fullDescription: 'A massive, party-sized platter of our signature smoky Jollof rice, expertly seasoned to feed a crowd and spark any celebration.',
      category: 'rice',
      protein: true
    },
    {
        id:7,
      image: '/ftray1.jpg',
      description: 'Giant platter of savory stir-fried rice loaded with vibrant vegetables.',
      price: '50.00',
      name: 'Fried Rice Tray',
      fullDescription: 'A celebratory tray of golden stir-fried rice, packed with seasoned vegetables and aromatic spices, designed to satisfy every guest at your event.',
      category: 'rice',
      protein: true
    },
    {
        id:8,
      image: '/chick1.jpg',
      description: 'Crispy, golden-brown fried chicken seasoned with a secret spice blend.',
      price: '25.00',
      name: 'Fried Chicken Plate',
      fullDescription: 'Tender, succulent chicken pieces deep-fried to golden perfection, featuring a crunchy, well-seasoned crust that locks in every drop of savory flavor.',
      category: 'protein',
    },
    {
        id:9,
      image: '/turkey1.jpg',
      description: 'Succulent, deep-fried turkey chunks seasoned with bold, savory West African spices.',
      price: '30.00',
      name: 'Grilled/Fried Turkey Plate',
      fullDescription: 'Tender, meaty turkey pieces fried to a golden crisp and tossed in a flavorful blend of aromatic herbs and traditional seasonings.',
      category: 'protein',
    },
    {
        id:10,
      image: '/fish2.jpg',
      description: 'Crispy fried or grilled croaker fish seasoned with bold spices.',
      price: '25.00',
      name: 'Fried Croaker Fish Plate',
      fullDescription: 'A whole, succulent croaker fish expertly seasoned and fried to perfection, offering a tender, flaky interior and a deliciously crisp, golden skin.',
      category: 'protein',
    },
    {
        id:11,
      image: '/egusi.jpg',
      description: 'Rich melon seed soup with spinach, traditional spices, and assorted meats.',
      price: '25.99',
      name: 'Egusi Soup',
      fullDescription: 'A savory melon seed soup blended with leafy greens and aromatic spices, creating a rich, textured delight that pairs perfectly with any swallow.',
      category: 'soup',
    },
    {
        id:12,
      image: '/ogbono1.jpg',
      description: 'Silky, draw-style wild mango seed soup with rich African spices.',
      price: '25.99',
      name: 'Ogbono Soup',
      fullDescription: 'A thick, hearty soup made from ground wild mango seeds, slow-cooked with assorted meats and fish for a smooth, savory, traditional finish.',
      category: 'soup',
    },
    {
        id:13,
      image: '/efo1.jpg',
      description: 'Rich spinach stew simmered with locust beans, peppers, and assorted meats.',
      price: '25.99',
      name: 'Eforiro Soup',
      fullDescription: 'A vibrant, slow-cooked spinach stew featuring a bold blend of peppers, savory locust beans, and an assortment of tender, seasoned meats.',
      category: 'soup',
    },
    {
        id:14,
      image: '/nsala.jpg',
      description: 'A rich, aromatic white soup thickened with mashed yam and seasoned with traditional spices.',
      price: '25.00',
      name: 'Nsala Soup w Chicken/Fish',
      fullDescription: 'A rich, aromatic white soup thickened with mashed yam and seasoned with traditional spices, featuring tender, flavorful catfish and savory meats.',
      category: 'soup'
    },
    {
        id:15,
      image: '/bitter2.jpg',
      description: 'Rich, savory soup prepared with washed bitterleaves and assorted meats.',
      price: '25.00',
      name: 'BitterLeaf Soup ',
      fullDescription: 'A traditional, thick soup made with thoroughly washed bitterleaves, cocoyam paste, and a blend of rich, aromatic Nigerian spices.',
      category: 'soup',
    },
    {
        id:16,
      image: '/okro2.jpg',
      description: 'Vibrant, slimy okra soup simmered with shrimp and assorted meats.',
      price: '25.99',
      name: 'Okro Soup',
      fullDescription: 'A deliciously thick and crunchy okra soup, perfectly seasoned with traditional spices, seafood, and a mix of tender, savory meats',
      category: 'soup',
    },
    {
        id:17,
      image: '/banga.jpg',
      description: 'Creamy palm nut soup infused with aromatic spices and assorted fish.',
      price: '27.00',
      name: 'Banga Soup',
      fullDescription: 'A rich, palm fruit-based soup slow-cooked with a unique blend of traditional spices, tender meats, and flavorful fresh seafood.',
      category: 'soup',
    },
    {
        id:18,
      image: '/afang.jpg',
      description: 'A nutrient-rich, thick soup made with shredded Afang leaves and waterleaf.',
      price: '30.00',
      name: 'Afang Soup',
      fullDescription: 'A deeply flavorful, textured soup prepared with finely ground Afang leaves and fresh waterleaf, slow-cooked with periwinkles, assorted meats, and traditional smoked fish.',
      category: 'soup',
    },
    {
        id:19,
      image: '/oha.jpg',
      description: 'Creamy, aromatic soup thickened with cocoyam and seasoned with fresh Oha leaves.',
      price: '30.00',
      name: 'Oha Soup',
      fullDescription: 'A delicate and flavorful soup made from tender Oha leaves and cocoyam paste, enriched with traditional spices like ogiri, and simmered with assorted meats and stockfish.',
      category: 'soup',
    },
    {
        id:20,
      image: '/semo.jpg',
      description: 'Smooth, firm, and satisfying semolina-based swallow.',
      price: '5.99',
      name: 'Semo',
      fullDescription: 'A finely milled semolina mash, expertly prepared to a smooth, stretchy consistency that perfectly complements any rich Nigerian soup.',
      category: 'extra',
    },
    {
        id:21,
      image: '/poundo.jpg',
      description: 'A premium, lump-free yam mash with a soft and pliable texture',
      price: '5.99',
      name: 'Poundo',
      fullDescription: 'A premium, lump-free yam mash with a soft, pliable texture, expertly prepared to provide the perfect neutral base for any rich or spicy Nigerian soup.',
      category: 'extra',
    },
    {
        id:22,
      image: '/eba.jpg',
      description: 'Zesty, textured swallow made from finely toasted cassava flakes.',
      price: '5.99',
      name: 'Garri',
      fullDescription: 'A firm and savory cassava mash, expertly prepared with boiling water to achieve a uniquely grainy yet pliable texture that pairs perfectly with any rich, draw-style soup.',
      category: 'extra',
    },
    {
        id:23,
      image: '/amala.jpg',
      description: 'Rich, earthy, and velvety swallow made from dried yam flour',
      price: '5.99',
      name: 'Amala',
      fullDescription: 'A classic, dark-textured mash prepared from premium sun-dried yam flour, whipped to a soft, stretchy consistency that is the traditional soulmate for Ewedu and Gbegiri',
      category: 'extra',
    },
    {
        id:24,
      image: '/fufu.jpg',
      description: 'Smooth, dense, and naturally fermented cassava-based swallow',
      price: '5.99',
      name: 'fufu',
      fullDescription: 'A hearty, traditional cassava mash boiled and pounded to a perfectly smooth, heavy consistency, offering a subtle fermented tang that pairs beautifully with rich, spicy soups',
      category: 'extra',
    },
    {
        id:25,
      image: '/soft drinks.jpg',
      description: 'A refreshing selection of chilled, sparkling sodas in various fruity and classic flavors.',
      price: '1.99',
      name: 'Soft Drinks',
      fullDescription: 'A diverse range of ice-cold carbonated beverages, offering a crisp and bubbly finish to complement any spicy or savory Nigerian meal.',
      category: 'drinks',
    },
    {
        id:26,
      image: '/juices.jpg',
      description: 'Pure, refreshing fruit juices pressed from the finest seasonal harvests',
      price: '2.99',
      name: 'Juices',
      fullDescription: 'A vibrant selection of chilled, naturally sweet juices, expertly extracted from sun-ripened fruits to provide a crisp, vitamin-rich accompaniment to any dish',
      category: 'drinks',
    },
    {
        id:27,
      image: '/zobo1.jpg',
      description: 'A chilled, vibrant hibiscus tea infused with ginger and natural spices.',
      price: '7.99',
      name: 'Zobo Drink - Small',
      fullDescription: 'A deeply refreshing, deep-red herbal infusion made from dried hibiscus petals, slow-steeped with spicy ginger, cloves, and a hint of fruity sweetness.',
      category: 'drinks',
    },
    {
        id:28,
      image: '/zobo2.jpg',
      description: 'A chilled, vibrant hibiscus tea infused with ginger and natural spices.',
      price: '9.99',
      name: 'Zobo Drink - Big',
      fullDescription: 'A deeply refreshing, deep-red herbal infusion made from dried hibiscus petals, slow-steeped with spicy ginger, cloves, and a hint of fruity sweetness.',
      category: 'drinks',
    },
    {
        id:29,
      image: '/tiger1.jpg',
      description: 'A creamy, naturally sweet milk made from crushed tigernuts and dates.',
      price: '9.99',
      name: 'Tigernut Drink',
      fullDescription: 'A chilled, velvety blend of nutrient-rich tigernuts, fiber-packed dates, and a hint of spicy ginger, offering a smooth and refreshing dairy-free treat.',
      category: 'drinks',
    },
    
]