export const foodData = [

    {
        id:1,
      image: '/jrice1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '26.99',
      name: 'Jollof Rice',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      protein: true,
      category: 'rice'

    },
    {
        id:2,
      image: '/fried2.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.99',
      name: 'Fried Rice',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'rice',
      protein: true
    },
    {
        id:3,
      image: '/coconut1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '26.99',
      name: 'coconut rice',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'rice',
      protein: true
    },
    {
        id:4,
      image: '/ofada1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.00',
      name: 'Ayamase Sauce w/White Rice',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'rice',
      protein: false
    },
    {
        id:5,
      image: '/stew1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '20.00',
      name: 'White Rice & Stew',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'rice',
      protein: false
    },
    {
        id:6,
      image: '/jtray1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '50.00',
      name: 'Jollof Rice Tray',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'rice',
      protein: true
    },
    {
        id:7,
      image: '/ftray1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '50.00',
      name: 'Fried Rice Tray',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'rice',
      protein: true
    },
    {
        id:8,
      image: '/chick1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.00',
      name: 'Fried Chicken Plate',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'protein',
    },
    {
        id:9,
      image: '/turkey1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '30.00',
      name: 'Grilled/Fried Turkey Plate',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'protein',
    },
    {
        id:10,
      image: '/fish2.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.00',
      name: 'Fried Croaker Fish Plate',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'protein',
    },
    {
        id:11,
      image: '/egusi.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.99',
      name: 'Egusi Soup',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:12,
      image: '/ogbono1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.99',
      name: 'Ogbono Soup',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:13,
      image: '/efo1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.99',
      name: 'Eforiro Soup',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:14,
      image: '/nsala.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.00',
      name: 'Nsala Soup w Chicken/Fish',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:15,
      image: '/bitter2.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.00',
      name: 'BitterLeaf Soup ',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:16,
      image: '/okro2.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '25.99',
      name: 'Okro Soup',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:17,
      image: '/banga.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '27.00',
      name: 'Banga Soup',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:18,
      image: '/afang.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '30.00',
      name: 'Afang Soup',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:19,
      image: '/oha.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '30.00',
      name: 'Oha Soup',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'soup',
    },
    {
        id:20,
      image: '/semo.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '5.99',
      name: 'Semo',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'extra',
    },
    {
        id:21,
      image: '/poundo.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '5.99',
      name: 'Poundo',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'extra',
    },
    {
        id:22,
      image: '/eba.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '5.99',
      name: 'Garri',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'extra',
    },
    {
        id:23,
      image: '/amala.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '5.99',
      name: 'Amala',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'extra',
    },
    {
        id:24,
      image: '/fufu.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '5.99',
      name: 'fufu',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'extra',
    },
    {
        id:25,
      image: '/soft drinks.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '1.99',
      name: 'Soft Drinks',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'drinks',
    },
    {
        id:26,
      image: '/juices.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '2.99',
      name: 'Juices',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'drinks',
    },
    {
        id:27,
      image: '/zobo1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '7.99',
      name: 'Zobo Drink - Small',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'drinks',
    },
    {
        id:28,
      image: '/zobo2.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '9.99',
      name: 'Zobo Drink - Big',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'drinks',
    },
    {
        id:29,
      image: '/tiger1.jpg',
      description: 'rtygfyuiiuydaigfugfoi divciydgsu',
      price: '9.99',
      name: 'Tigernut Drink',
      fullDescription: 'teteyryrydyd dygueuufuf uueuueueue ydududuud udududu udududu',
      category: 'drinks',
    },
    
]